### ISSUE TITLE
i can't seem to install or use this python project from 

### ISSUE THREAD

**Issue by logax01** [cloudbase/coriolis#2]
Can someone please help me install and use this python project on windows 10/server r2 ?? i really need it to complete my project, i already installed the latest python version and installed requirements.txt but i can't seem to know what to do next. This is the first time i download a github project so please help me. I have no knowledge with python so bear with me.

**Comment by chenzhouzhao** [comment]
how  to  install  for a  starer
junior

**Comment by aznashwan** [comment]
Hello, and thank you for your interest in Coriolis!

Coriolis is a distributed system comprised of a handful of microservices, and depends on some common OpenStack components such as Keystone and Barbican, alongside a SQL database and an AMQP server such as RabbitMQ.
As a result, installing all of Coriolis' components and dependencies manually can be a pretty daunting task.

We offer pre-built VM images with all Coriolis components pre-installed and pre-configured to be used for PoC purposes.

If you are interested in trying Coriolis out, please feel free to reach out to us [via the contact form on our website](https://cloudbase.it/about/#contact), or via e-mail at sales@cloudbasesolutions.com

**Comment by chenzhouzhao** [comment]
> 有人可以帮我在Windows 10 / Server R2上安装和使用此python项目吗？我真的需要它来完成我的项目，我已经安装了最新的python版本并安装了requirements.txt，但我似乎不知道下一步该怎么做。这是我第一次下载github项目，请帮助我。我对python不了解，所以请多多包涵。

how  it ?  what then ?  i  want to kown  how  to do  like  you

**Comment by chenzhouzhao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Can you send me  the encapsulated link directly? , If a fool-style manual with one-click build scripts may be more conducive to promotion
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                赵陈洲
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 4/16/2021 19:26，Nashwan ***@***.***> wrote： 



Hello, and thank you for your interest in Coriolis!
Coriolis is a distributed system comprised of a handful of microservices, and depends on some common OpenStack components such as Keystone and Barbican, alongside a SQL database and an AMQP server such as RabbitMQ.
As a result, installing all of Coriolis' components and dependencies manually can be a pretty daunting task.
We offer pre-built VM images with all Coriolis components pre-installed and pre-configured to be used for PoC purposes.
If you are interested in trying Coriolis out, please feel free to reach out to us via the contact form on our website, or via e-mail at ***@***.***

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chenzhouzhao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        In addition, Coriolis would get a lot more traction if it could be integrated directly into OpenStack as a basic component 
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                赵陈洲
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 4/21/2021 ***@***.***> wrote： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Can you send me  the encapsulated link directly? , If a fool-style manual with one-click build scripts may be more conducive to promotion
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                赵陈洲
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 4/16/2021 19:26，Nashwan ***@***.***> wrote： 



Hello, and thank you for your interest in Coriolis!
Coriolis is a distributed system comprised of a handful of microservices, and depends on some common OpenStack components such as Keystone and Barbican, alongside a SQL database and an AMQP server such as RabbitMQ.
As a result, installing all of Coriolis' components and dependencies manually can be a pretty daunting task.
We offer pre-built VM images with all Coriolis components pre-installed and pre-configured to be used for PoC purposes.
If you are interested in trying Coriolis out, please feel free to reach out to us via the contact form on our website, or via e-mail at ***@***.***

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chenzhouzhao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        In addition, if Coriolis can form a large two-layer network with the VXLAN technology of the kernel, it will achieve the same L2CG as Huawei Cloud (link:  https://support.huaweicloud.com/intl/en-us/usermanual-vpc/vpc_l2cg_0003.html) function, to achieve single host particle migration and migration across data centers.  RDA Automated Migration Tool: http://www.huaweicloud-rda.com/  https://support.huaweicloud.com/intl/en-us/usermanual-vpc/vpc_l2cg_0000.html  
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 4/21/2021 ***@***.***> wrote： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        In addition, Coriolis would get a lot more traction if it could be integrated directly into OpenStack as a basic component 
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                赵陈洲
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 4/21/2021 ***@***.***> wrote： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Can you send me  the encapsulated link directly? , If a fool-style manual with one-click build scripts may be more conducive to promotion
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                赵陈洲
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 4/16/2021 19:26，Nashwan ***@***.***> wrote： 



Hello, and thank you for your interest in Coriolis!
Coriolis is a distributed system comprised of a handful of microservices, and depends on some common OpenStack components such as Keystone and Barbican, alongside a SQL database and an AMQP server such as RabbitMQ.
As a result, installing all of Coriolis' components and dependencies manually can be a pretty daunting task.
We offer pre-built VM images with all Coriolis components pre-installed and pre-configured to be used for PoC purposes.
If you are interested in trying Coriolis out, please feel free to reach out to us via the contact form on our website, or via e-mail at ***@***.***

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
